### PR TITLE
FIX: Add arm64 builds

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Should add arm64 support. Not 100% sure if I need to bump the build number but seems safer to do so.

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by mscheltienne** [comment]
Shouldn't the build be defined in the `recipe` somehow? It seems strange to modify something outside of what could be submitted to `staged-recipes` for inclusion.

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
AFAIK it's independent. Maybe it's possible to have it be part of the staged recipes, not sure...

**Comment by larsoner** [comment]
FYI pushed a commit to try aarch64 and ppc64le, if they work with no effort then why not have them. But if it doesn't work trivially then I'll remove them and we can push support in `antio` directly first

**Pull request merged**
